steps:
  - label: ":test_tube: Run tests"
    command: "echo 'Running tests....' 'Success!'"
    key: "unit-tests"

  - command: "deploy.sh"
    label: ":rocket: Deploy to dev/qa"
    key: "deploy-qa"
    branches: "main"
    concurrency: 1
    concurrency_group: 'deploy/qa'
    depends_on:
      - "unit-tests"

  - block: "Release"
    branches: "main"
    prompt: "Fill out the details for release"
    depends_on:
      - "deploy-qa"
    fields: 
      - text: "Release Name"
        key: "release-name"
        hint: "Think of a cool name for this release"
      - text: "Changelog"
        key: "release-notes"
        required: false
        hint: "List of what's changed in this release"
      - select: "Type"
        key: "release-type"
        default: "beta"
        options:
        - label: "Beta"
          value: "beta"
        - label: "Stable"
          value: "stable"

  - command: release.sh
    label: ":rocket: Create release branch"
    branches: "main"
